<a href="https://colab.research.google.com/github/byhqsr/CodeRepo/blob/main/Pertemuan_2_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY - Multidimensional Data Arrays

It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. NumPy brings the computational power of languages like C and Fortran to Python, a language much easier to learn and use.

In [3]:
import numpy as np

In [4]:
np.__version__

'1.18.5'

In [5]:
print(np.info(np.add))

None


## What is Array?

![](image/array.png)

In [6]:
# Python List

a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

In [7]:
print(a+b)
print(a*b)

[1, 2, 3, 4, 5, 6, 7, 8]


TypeError: ignored

In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is *array*. 



In [8]:
a_array = np.array(a)
b_array = np.array(b)

print(a_array + b_array)
print(a_array * b_array)

[ 6  8 10 12]
[ 5 12 21 32]


## Creating `numpy` arrays

There are some ways to initialize new numpy arrays:
* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.
* reading data from files

### Lists

In [9]:
# vector: the argument to the array function is a list
v = np.array([1, 2, 3, 4, 5])

v

array([1, 2, 3, 4, 5])

In [10]:
# matrix: the argument to the array function is a nested list
m = np.array([[1, 2, 3], [4, 5, 6]])

m

array([[1, 2, 3],
       [4, 5, 6]])

The `v` and `m` objects are both of the type `ndarray` that the `numpy` module provides.

In [11]:
type(v), type(m)

(numpy.ndarray, numpy.ndarray)

In [12]:
a = [1,2,3]

In [13]:
type(a)

list

The difference between the `v` and `m` arrays is only their shapes. We can get information about the shape of an array by using the `ndarray.shape` property.

In [14]:
v.shape

(5,)

In [15]:
m.shape

(2, 3)

The number of elements in the array is available through the `ndarray.size` property

In [16]:
m.size

6

`numpy.ndarray` looks very similiar to the `list`. So, why not use the list instead?
`numpay.ndarray` is used for several reason:
1. Lists are very general. They can contain any kind of object. They do not support mathematical functions such as matrix and dot multiplication, etc. 
2. Numpy arrays are statically typed and homogenous. The type of the elements is determined when the array is created
3. Numpy arrays are memory efficient
4. It is fast for implementation of mathematical function

We can see the type of data of an array using `dtype`

In [18]:
m.dtype

dtype('int64')

If we want, we can explicitly define the type of the array data when we create it, using the `dtype` keyword argument: 

In [19]:
m = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)

m

array([[1., 2., 3.],
       [4., 5., 6.]])

Common data types that can be used with `dtype` are: `int`, `float`, `complex`, `bool`, `object`, etc.

### Create Matrix Zeros

In [20]:
# One dimension

zeros_matrix = np.zeros(5)

zeros_matrix

array([0., 0., 0., 0., 0.])

In [21]:
#two dimension

zeros_matrix2 = np.zeros(5,2)

TypeError: ignored

In [22]:
# should  be in tuple format

zeros_matrix2 = np.zeros((5,2)) # 5 rows, 2 columns
zeros_matrix2 

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

### Matrix ones

In [23]:
#one dimension

matrix_ones = np.ones(5)
matrix_ones 

array([1., 1., 1., 1., 1.])

In [24]:
#3 dimension

matrix_ones2 = np.ones((3, 4, 2)) #3 rows, 4 columns, 2 depth
matrix_ones2

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

## > Exercise 1

1. Create a matrix from a list which has 4 rows and 3 columns

In [25]:
my_matrix = np.array([[1,2,3],
                     [2,3,4],
                     [1,2,1],
                     [1,2,2]])
my_matrix

array([[1, 2, 3],
       [2, 3, 4],
       [1, 2, 1],
       [1, 2, 2]])

2. Create the following matrix
![](image/lat11.png)

In [26]:
my_matrix2 = np.array([[2,7,12,0],
                      [3,9,3,4],
                      [4,0,1,3]])
my_matrix2

array([[ 2,  7, 12,  0],
       [ 3,  9,  3,  4],
       [ 4,  0,  1,  3]])

3. Create a 2D matrix with size of 10

In [27]:
cara1 = np.array([[1,2,3,4,5],
                 [6,7,8,9,10]])
cara1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [28]:
cara2 = np.zeros((2,5))
cara2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
cara3 = np.array([[1,2],
                 [2,2],
                 [2,1],
                 [3,3],
                 [4,5]])
cara3

array([[1, 2],
       [2, 2],
       [2, 1],
       [3, 3],
       [4, 5]])

In [31]:
cara4 = np.array([[1],
                 [2],
                 [2],
                 [3],
                 [4],
                 [9],
                 [10],
                 [10],
                 [7],
                 [1]])
cara4

array([[ 1],
       [ 2],
       [ 2],
       [ 3],
       [ 4],
       [ 9],
       [10],
       [10],
       [ 7],
       [ 1]])

In [32]:
print("Size cara1: ", cara1.size)
print("Size cara2: ", cara2.size)
print("Size cara3: ", cara3.size)
print("Size cara4: ", cara4.size)

Size cara1:  10
Size cara2:  10
Size cara3:  10
Size cara4:  10


In [33]:
print("Shape cara1: ", cara1.shape)
print("Shape cara2: ", cara2.shape)
print("Shape cara3: ", cara3.shape)
print("Shape cara4: ", cara4.shape)

Shape cara1:  (2, 5)
Shape cara2:  (2, 5)
Shape cara3:  (5, 2)
Shape cara4:  (10, 1)


4. Create a 3D matrix of ones which has 2 rows, 3 columns, and 3 depth

In [34]:
m4 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               
                [[6,2,3],
                [4,5,8],
                [8,8,9]]])

m4

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[6, 2, 3],
        [4, 5, 8],
        [8, 8, 9]]])

In [35]:
m4.shape

(2, 3, 3)

5. Make the following arrays from zeros arrays and with for loops
![](image/exercise1.png)

In [36]:
my_array = np.zeros((5,3))
my_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
for i in my_array:
    print(i+2)

[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]


### Using array-generating functions

For larger arrays it is inpractical to initialize the data manually, using explicit python lists. Instead we can use one of the many functions in `numpy` that generate arrays of different forms. Some of the more common are:

**arange**

In [37]:
# create a range

x = np.arange(10)

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
# create a range

x = np.arange(10, 20) # arguments: start, stop

x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
# create a range

x = np.arange(10, 20, 2) # arguments: start, stop, step

x

array([10, 12, 14, 16, 18])

In [ ]:
x = np.arange(-1, 1, 0.1)

x

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

The number 9.00000000e-01 already is a floating point number.
It's written in scientific notation and is equivalent to 9 * 10**-1 or 0.9.

#### linspace

In [ ]:
# using linspace, both end points ARE included
np.linspace(0, 10, 10) #Unlike arange that uses step, linspace uses the number of sample

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

#### random data

In [ ]:
from numpy import random

In [ ]:
#uniform random numbers in [0,1]
random.rand(5,5)

array([[0.68886226, 0.80376421, 0.68511052, 0.05933548, 0.00609701],
       [0.71453569, 0.98785297, 0.905757  , 0.56097693, 0.26333855],
       [0.13570713, 0.98642657, 0.48538833, 0.20870015, 0.59357451],
       [0.51402483, 0.30974573, 0.23055402, 0.52798755, 0.17149748],
       [0.24462066, 0.14881871, 0.72438958, 0.42477621, 0.66295972]])

In [ ]:
# standard normal distributed random numbers
x = random.randn(5,5)
x

array([[ 1.22268108, -0.11597117,  1.04261376, -1.85356452,  0.27452336],
       [-0.42800941, -0.01834765,  1.15716121,  0.36945645,  1.70644982],
       [ 0.344245  ,  0.4125159 , -0.22873644, -2.04407581, -0.46607386],
       [-1.59228872,  0.26495182,  0.55572725, -0.00871542, -0.04690909],
       [ 0.2984943 , -1.8564972 ,  0.7993992 , -0.90392802, -0.32273761]])

In [ ]:
x.dtype

dtype('float64')

In [ ]:
x = np.ones(2, dtype = np.int64)
x

array([1, 1], dtype=int64)

In [ ]:
random.randint(10)

4

In [ ]:
random.randint(2, 10, size=4)

array([5, 3, 9, 7])

In [ ]:
random.randint(2, 10, size=(4,2,2))

array([[[3, 4],
        [4, 5]],

       [[9, 7],
        [7, 4]],

       [[8, 9],
        [3, 2]],

       [[2, 6],
        [2, 5]]])

## Exercise 2

1. Generate a 1-D array containing 5 random integers from 0 to 100:

In [ ]:
random.randint(0,100, size=5)

array([83, 75, 78,  6, 31])

2. Generate a 2-D array with 3 rows, each row contains 5 random integers from 0 to 100

In [ ]:
random.randint()

3. Generate a 1-D array of 30 evenly spaced elements between 1.5 and 5.5, inclusive.

## Adding, removing, and sorting elements

In [ ]:
# Append

my_arr = np.arange(10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.append(my_arr, (10, 11, 12))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

When axis is specified, values must have the correct shape.

In [ ]:
my_arr1 = np.array([[1,2,3],
                    [2,4,6]])

In [ ]:
np.append(my_arr1, [[2,1,1]], axis=0)

array([[1, 2, 3],
       [2, 4, 6],
       [2, 1, 1]])

In [ ]:
a = np.array([[1, 2, 8], [5, 8, 10]])
b = np.array([[8, 2, 1], [3, 9, 1]])
c = np.concatenate((a, b), axis = 0)
print(c)

[[ 1  2  8]
 [ 5  8 10]
 [ 8  2  1]
 [ 3  9  1]]


In [ ]:
x = np.array([[1,2,3], [1,1,1]])
y = np.array([[3,3,1], [1,2,3]])
x = np.concatenate((x, y), axis = 1)
print(x)

[[1 2 3 3 3 1]
 [1 1 1 1 2 3]]


In [ ]:
# sorting np.sort()
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [ ]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#Concatenate arrays

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [ ]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

np.concatenate((x,y), axis=0) #if axis = None, then arrays are flatten before use

array([[1, 2],
       [3, 4],
       [5, 6]])

### delete elements of an array

In [ ]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.delete(arr, 1, axis=0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

## Shape and Size of an array

`ndarray.ndim` : the number of axes \
`ndarray.size` : the total number of element \
`ndarray.shape` : the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [ ]:
my_array = np.array([[[0, 1, 2, 3],
                      [4, 5, 6, 7]],
                          
                      [[0, 1, 2, 3],
                      [4, 5, 6, 7]],
                         
                      [[0 ,1 ,2, 3],
                      [4, 5, 6, 7]]])

In [ ]:
my_array.ndim

3

In [ ]:
my_array.size

24

In [ ]:
my_array.shape

(3, 2, 4)

### Reshaping an array

When you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

In [ ]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [ ]:
a.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

## > Exercise 3

1. create a 3x3 matrix with values ranging from 2 to 10

In [ ]:
x =np.arange(2,11).reshape(3,3)
x

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

2. concentenate the following arrays \
**[[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]**
![](image/lat3.png)

### Converting a 1D array into 2D array (add a new axis to an array)

You can use `np.newaxis` and `np.expand_dims` to increase the dimensions of your existing array.

`np.newaxis` will increase the dimension of array by one whe it is used once. \
1D -> 2D, 2D -> 3D, and so on

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [ ]:
# convert a 1D array to a row vector by inserting an axis along the first dimension
a2 = a[np.newaxis, :]
a2

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
a2.shape

(1, 6)

In [ ]:
# for a column vector, you can insert an axis along the second dimension
a3 = a[:, np.newaxis]
a3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
a3.shape

(6, 1)

using `np.expand_dims`

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [ ]:
# You can use np.expand_dims to add an axis at index position 1
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [ ]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
# You can add an axis at index position 0 with
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

## Indexing and slicing

In [ ]:
data = np.array([1, 2, 3, 4, 5])

In [ ]:
data[1]

2

In [ ]:
data[:3]

array([1, 2, 3])

In [ ]:
data[1:]

array([2, 3, 4, 5])

In [ ]:
data[-2:]

array([4, 5])

![](image/numpy.jpg)

You may want to take a section of your array or specific array elements to use in further analysis or additional operations. To do that, you’ll need to subset, slice, and/or index your arrays.

If you want to select values from your array that fulfill certain conditions, it’s straightforward with NumPy.

In [ ]:
a = np.array([[1 , 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

You can easily print all of the values in the array that are less than 5.

In [ ]:
print(a[a < 5])

[1 2 3 4]


You can also select, for example, numbers that are equal to or greater than 5, and use that condition to index an array.

In [ ]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [ ]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


Or you can select elements that satisfy two conditions using the & and | operators:

In [ ]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [ ]:
# pipe, or, vertical bar: |
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[1,1:3]

array([6, 7])

In [ ]:
z = np.array([[[0, 1, 3],
               [5, 7, 9]],
              
              [[0, 2, 4],
               [6, 8, 10]]])
z

array([[[ 0,  1,  3],
        [ 5,  7,  9]],

       [[ 0,  2,  4],
        [ 6,  8, 10]]])

In [ ]:
z.shape

(2, 2, 3)

In [ ]:
z[0] # access row 0

array([[0, 1, 3],
       [5, 7, 9]])

In [ ]:
z[0,1] # access row 0, column 1

array([5, 7, 9])

In [ ]:
z[1, 1, 1:] #access row 1, column 1, depth 1-2

array([ 8, 10])

In [ ]:
a = np.array([1,3,1,4,5,2,1])
a

array([1, 3, 1, 4, 5, 2, 1])

In [ ]:
a[1:4]

array([3, 1, 4])

In [ ]:
a

array([ 1,  3,  1, 10,  5,  2,  1])

## > Exercise 4

1. create a null vector / 1D array of size 10 and update fifth value to 11.

In [40]:
x = np.zeros(10)
print(x)
print("Update fifth value to 11")
x[5] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update fifth value to 11
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


2. Write a NumPy program to create a 2x3 arrays and change it into 3x2 arrays

In [41]:
x = np.array([1, 2, 3, 4, 5, 6])
y = np.reshape(x,(2,3))
print("Reshape 2x3:")
print(y)
z = np.reshape(x,(3,2))
print("Reshape 3x2:")
print(z)

Reshape 2x3:
[[1 2 3]
 [4 5 6]]
Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]


3. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.
![](image/lat1.png)

In [42]:
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


4. Take a look at the following matrix. Access the [2, 1,1]

In [45]:
z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])
z[2,1,1]

2

# Creating an array from existing data

You can easily use create a new array from a section of an existing array.

In [ ]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

You can also stack two existing arrays, both vertically and horizontally. Let’s say you have two arrays, a1 and a2:

In [ ]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [ ]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

using `hstack`

In [ ]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

You can split an array into several smaller arrays using `hsplit`. You can specify either the number of equally shaped arrays to return or the columns after which the division should occur.

In [ ]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

If you wanted to split this array into three equally shaped arrays, you would run:

In [ ]:
y = np.hsplit(x, 3)
y

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

If you want to split your array after the third and fourth column, you’d run:

In [ ]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
z = np.hsplit(x, (3, 5))

z

[array([[ 1,  2,  3],
        [13, 14, 15]]), array([[ 4,  5],
        [16, 17]]), array([[ 6,  7,  8,  9, 10, 11, 12],
        [18, 19, 20, 21, 22, 23, 24]])]

In [ ]:
m = np.hsplit(x, (1,3))

m

[array([[ 1],
        [13]]), array([[ 2,  3],
        [14, 15]]), array([[ 4,  5,  6,  7,  8,  9, 10, 11, 12],
        [16, 17, 18, 19, 20, 21, 22, 23, 24]])]

# Basic array operations

In [ ]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)



array([2, 3])

In [ ]:
data

array([1, 2])

In [ ]:
ones

array([1, 1])

In [ ]:
data + ones

array([2, 3])

![](image/"np_data_plus_ones.png")

In [ ]:
data - ones

array([0, 1])

In [ ]:
data * data

array([1, 4])

In [ ]:
data / data

array([1., 1.])

In [ ]:
a = np.array([1, 2, 3, 4])

a.sum()

10

sum the rows/columns

In [ ]:
b = np.array([[1, 1],
              [2, 2]])
b.sum(axis=0)

array([3, 3])

In [ ]:
b.sum(axis=1)

array([2, 4])

# Broadcasting

There are times when you might want to carry out an operation between an array and a single number (also called an operation between a vector and a scalar) or between arrays of two different sizes. For example, your array (we’ll call it “data”) might contain information about distance in miles but you want to convert the information to kilometers. You can perform this operation with:

In [ ]:
data = np.array([1.0, 2.0])
data * 1.6

![](image/np_multiply_broadcasting.png)

NumPy understands that the multiplication should happen with each cell. That concept is called <b> broadcasting </b>. Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes. 

# Working with Mathematical Formulas

The ease of implementing mathematical formulas that work on arrays is one of the things that make NumPy so widely used in the scientific Python community.

![](image/np_MSE_formula.png)

In [ ]:
mse = (1/n) * np.sum(np.square(y_pred - labels))

![](image/np_mse_viz1.png)

![](image/np_mse_viz2.png)

# How to save and load NumPy objects?

The ndarray objects can be saved to and loaded from the disk files with `loadtxt` and `savetxt` functions that handle normal text files, `load` and `save` functions that handle NumPy binary files with a .npy file extension, and a `savez` function that handles NumPy files with a .npz file extension.

If you want to store a single ndarray object, store it as a .npy file using np.save. If you want to store more than one ndarray object in a single file, save it as a .npz file using `np.savez`. You can also save several arrays into a single file in compressed npz format with `savez_compressed`.

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
np.save('myfile', a)

In [ ]:
# load file

b = np.load('myfile.npy')

In [ ]:
b

array([1, 2, 3, 4, 5, 6])

You can save a NumPy array as a plain text file like a .csv or .txt file with `np.savetxt`.

In [ ]:
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.savetxt('myfile2.csv', csv_arr)

In [ ]:
np.loadtxt('myfile2.csv')

array([1., 2., 3., 4., 5., 6., 7., 8.])

# ASSIGNMENT

1. Create a 4x4 matrix with values ranging from 0 to 3.\
(The following image is just as an example. It doesn't represent the real image of arrays in the question)
![](image/assignment2.png)

In [50]:
x = np.zeros((4,4))
print("Original array:")
print(x)
print("Row values ranging from 0 to 3.")
x += np.arange(4)
print(x)

Original array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Row values ranging from 0 to 3.
[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


2. Create and array with shape of 4x4 and turn it into two arrays along the second axis.\
![](image/assignment.png)

In [56]:
x = np.arange(16).reshape((4, 4))
print("Original array:")
print(x)
print("After splitting horizontally:")
print(np.hsplit(x, [2, 6]))

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
After splitting horizontally:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int64)]
